[project]
name = "pcc"
description = "USB to SQL Data Collection"
dynamic = ["readme", "version"]
authors = [{ name = "Glen Springle", email = "glenspringle@gmail.com" }]
maintainers = [{ name = "Glen Springle", email = "glenspringle@gmail.com" }]
requires-python = ">= 3.11"
license = {text = "Proprietary"}
dependencies = [
    "pyudev==0.24.4",
    "pyzmq==27.1.0",
    "pyserial==3.5",
    "argparse==1.4.0",
    "fastapi[standard]==0.136.1",
    "sqlmodel==0.0.38",
]

[project.optional-dependencies]
dev = [
    "tox",
    "build",
    "pytest",
    "pytest-cov",
]

[project.scripts]
pcc-monitor = "pcc.pcc_monitor:main"
pcc-aggregator = "pcc.pcc_aggregator:main"
fake_dispenser = "pcc.fake_dispenser:main"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}
version = {attr = "pcc.__version__"}

[build-system]
requires = [ "setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.distutils.egg_info]
egg_base = "build"

[tool.distutils.bdist_wheel]
universal = true

[tool.coverage.report]
omit = []

[tool.tox]
legacy_tox_ini = """

[tox]
isolated_build = True
envlist =
    clean
    py313

[testenv]
install_command=python -m pip install {opts}
depends =
deps =
    psutil
    setuptools
    wheel
    coverage
    pytest-cov
    pytest
commands = pytest -v --cov=./pcc --cov-append --cov-branch --cov-report=term-missing ./tests

[testenv:clean]
install_command =
    python -m pip install {opts} {packages}
deps = coverage[toml]
skip_install = true
commands = coverage erase
"""
